name: Deploy to Docker Hub
on:
  push:
    branches:
      - main
      
jobs:
   build-and-deploy:
    runs-on: ${{matrix.os}}
    strategy:
     matrix:
       os: [ubuntu-latest] #docker not supported on macOS for GAction
    
    steps:
     - name: Checkout code
       uses: actions/checkout@v2
       
     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
     - name: Build with Maven
       run: mvn -B package --file pom.xml
     
     - name: Log in to Docker Hub
       run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1
      
     - name: Build, tag, and push image to Amazon ECR
       env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: enum-v2-backend
        ECR_REPOSITORYS: enumv2_nginx
       run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:Latest .
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORYS:Latest -f Docker_nginx .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:Latest 
        docker push $ECR_REGISTRY/$ECR_REPOSITORYS:Latest 
        
     // - name: Download environment variables from S3
     //   run: |
     //      aws s3 cp s3://enumv2-env-variables/backend/prod/enumv2-backend-prod.env .
     //      cat enumv2-backend-prod.env 

     // - name: Set up environment variables
     //   run: |
     //      export $(cat enumv2-backend-prod.env)
         
     // - name: Update ECS service
     //   run: |
     //    aws ecs update-service --cluster enum-v2-production-server --service enumv2-prod-b --force-new-deployment
